### ISSUE TITLE
Bump apiextensions.k8s.io to v1

### ISSUE THREAD

**Issue by benedikt-bartscher** [jace-ys/sentry-operator#4]
Hey @jace-ys first of all, thank you for your great work on this operator, i really like the idea!
Are you still using it? Are there any plans to bump the apiextension group from v1beta which was deprecated in kubernetes v1.22?

**Comment by jace-ys** [comment]
@benedikt-bartscher I'm not actively working on this anymore, but feel free to open a PR if you'd like!

**Comment by benedikt-bartscher** [comment]
@jace-ys thank you for your response, i do not need this anymore since i created my own sentry operator with kopf.
